remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid_senior_level: true
  director: false
  executive: false

jobTypes:
  full_time: true
  contract: false
  part_time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all_time: false
  month: false
  week: false
  last_24_hours: true

positions:
  - software_engineer

locations:
  - Germany

apply_once_at_company: true

distance_km: 100

company_blacklist:
  - wayfair
  - crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: gpt-4o-mini
